spring.application.name=04-notifications-api

doubletick.api.key=key_uxchFwg4ziTdl7I9EcCFLeadAUqXKmzD6cCWP8GhCYndYwenGlJuecOiMXHCCp3FP7f96bR8akDrab5bUhzQGjdSzOLcLNO4ZsdoWad9Z4qCTA9eiWTmyZRxdT6hzsadcxVq0OKtMnys3hquGwnK7AC6A15XafrHYb5hzRHwRX4srSBQADGntxAQPL5BOggKReTwozHdVf4TAYZyDRR2C4F

doubletick.api.url=https://public.doubletick.io/whatsapp/message/template

kafka.topic.name=ashokit-orders
kafka.bootstrap.url=localhost:9092
